stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_COMMIT_SHA

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/emirys774/inception-of-things:$IMAGE_TAG .
    - docker push registry.gitlab.com/emirys774/inception-of-things:$IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  script:
    - kubectl set image deployment/my-app my-app=registry.gitlab.com/emirys774/inception-of-things:$IMAGE_TAG
  only:
    - main
