global:
  hosts:
    domain: local.gitlab
  ingress:
    configureCertmanager: false
    enabled: true
    annotations: {}
    tls:
      enabled: false

gitlab:
  webservice:
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 1
