BOX = "koalephant/debian12"
BOX_URL = "https://boxes.storage.koalephant.com/debian12/1.4.0/amd64/virtualbox.box"
COMMON_MEMORY = 1024
COMMON_CPUS = 1
INSTALLERS_PATH = "./installers/"

SERVER_MACHINE = "btanirS"
SERVER_IP = "192.168.56.110"
SERVER_SH = INSTALLERS_PATH + "server.sh"

PROVIDER = "virtualbox"
NETWORK = "private_network"
PROVISION = "shell"


Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.box_url = BOX_URL

  # Server Machine
  config.vm.define SERVER_MACHINE do |control|
    control.vm.hostname = SERVER_MACHINE
    control.vm.network NETWORK, ip: SERVER_IP   
    control.vm.synced_folder "./apps", "/vagrant", type: "virtualbox"
    control.vm.provider PROVIDER do |vb|
      vb.name = SERVER_MACHINE 
      vb.memory = COMMON_MEMORY
      vb.cpus = COMMON_CPUS
    end
    control.vm.provision PROVISION, path: SERVER_SH, args: [SERVER_IP]
  end
end
