# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  # Primary Machine
  config.vm.define "eyasaS" do |control|
    control.vm.hostname = "eyasaS"
    control.vm.network "private_network", ip: "192.168.56.110"    
    control.vm.provider "virtualbox" do |vb|
      vb.name = "btanirS" 
      vb.memory = 512
      vb.cpus = 1
    end
  end

  # Secondary Machine
  config.vm.define "eyasaSW" do |control|
    control.vm.hostname = "eyasaSW"
    control.vm.network "private_network", ip: "192.168.56.111"    
    control.vm.provider "virtualbox" do |vb|
      vb.name = "eyasaSW"     
      vb.memory = 512
      vb.cpus = 1
    end
  end
  
end
