# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  # Primary Machine
  config.vm.define "Server" do |server|
    server.vm.hostname = "Server"

    server.vm.network "private_network", ip: "192.168.56.110"    
    
    server.vm.provider "virtualbox" do |vb|
      vb.name = "btanir" 
      vb.memory = 512
      vb.cpus = 1
    end
  end

  # Secondary Machine
  config.vm.define "ServerWorker" do |worker|
    worker.vm.hostname = "ServerWorker"
    
    worker.vm.network "private_network", ip: "192.168.56.111"    

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "btanir"     
      vb.memory = 512
      vb.cpus = 1
    end
  end
  
end
